import React from "react";
import { Timeline } from "./ui/timeline";

export default function TimelineDemo() {
  const data = [
    {
      title: "2023-2024",
      content: (
        <div className="flex flex-col md:flex-row gap-4">
          <div className="flex-shrink-0 w-32">
            <img
              src="/images/Experience/Quantiphi.png"
              alt="Aceternity company logo"
              className="rounded-lg object-contain w-full shadow-[0_0_24px_rgba(34,_42,_53,_0.06),_0_1px_1px_rgba(0,_0,_0,_0.05),_0_0_0_1px_rgba(34,_42,_53,_0.04),_0_0_4px_rgba(34,_42,_53,_0.08),_0_16px_68px_rgba(47,_48,_55,_0.05),_0_1px_0_rgba(255,_255,_255,_0.1)_inset]"
            />
          </div>
          <div className="flex-1">
            <h3 className="text-lg md:text-xl font-bold text-gray-900 mb-1">Quantiphi</h3>
            <p className="text-neutral-900 dark:text-neutral-500 text-sm md:text-base font-medium mb-5">
              Machine Learning Engineer
            </p>
            <div className="text-neutral-600 dark:text-neutral-400 text-sm md:text-base">
            <ul className="list-disc pl-5 pr-3 md:pr-0 space-y-1">
                <li className="text-justify"> Developed and maintained the ML backend for ICICI Bank chatbots across platforms with over 10k daily active users.</li>
                <li className="mb-2 text-justify">Enhanced chatbot user interactions by 30% through optimization of an open-source model, leading to a 15% reduction in downtime.</li>
                <li className="mb-2 text-justify">Improved system scalability using Docker and Kubernetes, reducing deployment time by 25% and ensuring robust performance across all platforms.</li>
                <li className="mb-2 text-justify">Built and optimized end-to-end ML pipelines for TIAA using Google Contact Center AI, enabling sentiment analysis and topic tagging, and populating real time insights into dashboards with a 50% performance improvement via OOP and multiprocessing techniqu.</li>
                <li className="mb-2 text-justify">Researched and implemented Generative AI in private environments for a pharmaceutical company, achieving 93% accuracy in document-indexed responses by training models on sensitive data.</li>
            </ul>
            </div>
          </div>
        </div>
      ),
    },
    {
      title: "2022 (Aug-Dec)",
      content: (
        <div className="flex flex-col md:flex-row gap-4">
          <div className="flex-shrink-0 w-32">
            <img
              src="/images/Experience/Quantiphi.png"
              alt="Quantiphi Analytics PVT LTD"
              className="rounded-lg object-contain w-full shadow-[0_0_24px_rgba(34,_42,_53,_0.06),_0_1px_1px_rgba(0,_0,_0,_0.05),_0_0_0_1px_rgba(34,_42,_53,_0.04),_0_0_4px_rgba(34,_42,_53,_0.08),_0_16px_68px_rgba(47,_48,_55,_0.05),_0_1px_0_rgba(255,_255,_255,_0.1)_inset]"
            />
          </div>
          <div className="flex-1">
            <h3 className="text-lg md:text-xl font-bold text-gray-900 mb-1">Quantiphi</h3>
            <p className="text-neutral-900 dark:text-neutral-500 text-sm md:text-base font-medium mb-5">
            Machine Learning Engineer Intern
            </p>
            <div className="text-neutral-600 dark:text-neutral-400 text-sm md:text-base">
              <ul className="list-disc pl-5 pr-3 md:pr-0 space-y-1 text-justify">
                <li className="text-justify"> Designed a pipeline to monitor and analyze responses generated by the Flan-T5 model, ensuring quality and relevance.</li>
                <li className="mb-2 text-justify"> Applied LDA and Top2Vec algorithms for topic modeling on unsupervised conversation data, improving data insights.</li>
                <li className="mb-2 text-justify">Conducted code reviews and resolved issues during model training and deployment, reducing error rates by 12%.</li>
             </ul>
            </div>
          </div>
        </div>
      ),
    },
    {
        title: "2022",
        content: (
          <div className="flex flex-col md:flex-row gap-4">
            <div className="flex-shrink-0 w-32">
              <img
                src="/images/Experience/Sameer.png"
                alt="Sameer company logo"
                className="rounded-lg object-contain w-full shadow-[0_0_24px_rgba(34,_42,_53,_0.06),_0_1px_1px_rgba(0,_0,_0,_0.05),_0_0_0_1px_rgba(34,_42,_53,_0.04),_0_0_4px_rgba(34,_42,_53,_0.08),_0_16px_68px_rgba(47,_48,_55,_0.05),_0_1px_0_rgba(255,_255,_255,_0.1)_inset]"
              />
            </div>
            <div className="flex-1">
              <h3 className="text-lg md:text-xl font-bold text-gray-900 mb-1">Sameer</h3>
              <p className="text-neutral-900 dark:text-neutral-500 text-sm md:text-base font-medium mb-5">
              Research Intern
              </p>
              <div className="text-neutral-600 dark:text-neutral-400 text-sm md:text-base">
                <ul className="list-disc pl-5 pr-3 md:pr-0 space-y-1 text-justify">
                    <li className="text-justify"> Detect the cavity inside a tree and simulate it in a 3D plot using MATLAB. </li>
                <li className="mb-2 text-justify">Performed operations on SFCW waveform and took readings using 2 omni directional antenna.</li>
                <li className="mb-2 text-justify">Got hands on experience of Virtual Network Analyzer.</li>
                </ul>
              </div>
            </div>
          </div>
        ),
      },
    {
      title: "2021",
      content: (
        <div className="flex flex-col md:flex-row gap-4">
          <div className="flex-shrink-0 w-32">
            <img
              src="/images/Experience/Phemesoft.png"
              alt="Project logo"
              className="rounded-lg object-contain w-full shadow-[0_0_24px_rgba(34,_42,_53,_0.06),_0_1px_1px_rgba(0,_0,_0,_0.05),_0_0_0_1px_rgba(34,_42,_53,_0.04),_0_0_4px_rgba(34,_42,_53,_0.08),_0_16px_68px_rgba(47,_48,_55,_0.05),_0_1px_0_rgba(255,_255,_255,_0.1)_inset]"
            />
          </div>
          <div className="flex-1">
            <h3 className="text-lg md:text-xl font-bold text-gray-900 mb-1">Phemesoft</h3>
            <p className="text-neutral-900 dark:text-neutral-500 text-sm md:text-base font-medium mb-5">
              Android Developer Intern
            </p>
            <div className="text-neutral-600 dark:text-neutral-400 text-sm md:text-base">
                <ul className="list-disc pl-5 pr-3 md:pr-0 space-y-1">
                  <li className="text-justify"> Developed an attendance app with real-time geolocation tracking using Firebase.</li>
                  <li className="mb-2 text-justify">Incorporated a single-page login system with role-based access for Admin, Employer, and Employee users.</li>
                </ul>
            </div>
          </div>
        </div>
      ),
    },
  ];

  return (
    <section id="timeline" className="py-24 bg-white"> {/* Increased vertical padding */}
      <div className="container mx-auto px-4 md:px-8"> {/* Increased horizontal padding on medium screens */}
        <h2 className="text-4xl font-bold mb-16 text-center">Work Experience</h2> {/* Increased heading size and bottom margin */}
        <div className="max-w-4xl mx-auto"> {/* Increased max width of container */}
          <Timeline items={data} />
        </div>
      </div>
    </section>
  );
}